export {default as Header} from "../components/header/header"
export {default as Main} from "../components/main"
export {default as ContactUs} from "../components/contacts/contactUs"
export {default as Blog} from "../components/blog/blog"
export {default as Login} from "../components/auth/login"
export {default as Register} from "../components/auth/register"
export {default as Footer} from "../components/footer/mainFooter"
export {default as Navbar} from "../components/header/navbar/navbar"
export {default as TemperamentSurvey} from "../components/TemperamentSurvey/TemperamentSurvey"
export {default as Viewplants} from "../components/plants/viewPlants"
export {default as NotFound} from "../components/notFound/notFound"
export {default as Difference} from "../components/blog/Difference _in_temperament"
export {default as Change_mood} from "../components/blog/change_mood"