export let plants = [
    {
        name: "زنجبیل",
        avatarUrl: "../../images/plants/zanjebil.png",
        latinName: "Ginger",
        properties: "ضد التهابی ، افزایش سیستم ایمنی ، ضد تهوع",
        Uses: "درمان سرفه، سرما خوردگی ، تسکین درد عضلانی ، کمک به بیماری های قلبی عروقی",
        preparation: "میتوان آن را به صورت ریشه زنجبیل تازه یا روغن زنجبیل استفاده کرد.",
        side_effects: "عوارض احتمالی شامل تحریک گوارش ، حساسیت پوستی  و تحریک سیستم عصبی است",
    },
    {
        name: "چای سبز",
        avatarUrl: "../../images/plants/chaee sabz.png",
        latinName: "Green Tee",
        properties: "آنتی اکسیدانی ، افزایش سیستم ایمنی ، ضد التهابی",
        Uses: "کمک به کاهش وزن ، پیشگیری و درمان سرطان ، جلوگیری از پیری زودرس",
        preparation: "میتوان آنرا به صورت برگ چای سبز یا به عنوان مکمل غذایی مصرف کرد",
        side_effects: "عوارض احتمالی شامل اظطراب ، افزایش ضربان قلب ، اسیدیته معده و اختلالات خواب است",
    },
    {
        name: "گل گاو زبان",
        avatarUrl: "../../images/plants/gol gav zaban.png",
        latinName: "Borage",
        properties: "ضد التهابی ، تسکین درد مفاصل ، افزایش سیستم ایمنی ، فواید گوارشی.",
        Uses: "درمان سرفه های مزمن ، ضد پیری ، کمک به آسم های خفیف",
        preparation: "میتوان آنرا به صورت برگ گل گاو زبان ویا به شکل مکمل غذایی مصرف کرد.",
        side_effects: "عوارض احتمالی شامل حساسیت پوستی ، سر گیجه و تحریک سیستم عصبی هستند.",
    },
    {
        name: "اویشن",
        avatarUrl: "../../images/plants/avishan.png",
        latinName: "Thyme",
        properties: "ضد عفونی کننده ، ضد التهابی ، تسکین درد مفاصل ، افزایش سیستم ایمنی و فواید گوارشی.",
        Uses: "درمان سرفه و سرما خوردگی ،تسکین درد مفاصل ، درمان گلو درد",
        preparation: "به صورت دمنوش میتوان استفاده کرد ، همچنین میتوان در غذا نیز استفاده کرد",
        side_effects: "عوارض احتمالی شامل حساسیت پوستی و تحریک سیستم عصبی هستند",
    },
    {
        name: "سنبل الطیب",
        avatarUrl: "../../images/plants/sonbolaltayb.png",
        latinName: "Valerian",
        properties: "خواص آرام بخش ،ضد اظطراب ، مسکن عضلانی و تسکین خشکی عضلانی است.",
        Uses: "درمان کرم معده و روده ، برطرف کننده اتفراغ ، اتبام دهنده زخم پا",
        preparation: "میتوان آن را به صورت ریشه سنبل الطیب استفاده کرد",
        side_effects: "عوارض احتمالی شامل خواب آلودگی ، سرگبجه و اختلالات گوارشی هستند.",
    },
    {
        name: "بابونه",
        avatarUrl: "../../images/plants/babooneh.png",
        latinName: "Chamomile",
        properties: ".ضد التهابی ، آرامشبخش ، تسکین درد و تسکین خشکی عضلانی ، کمک به هضم غذا و ضد افسردگی و اظطراب",
        Uses: ".مفید برای پوست ، درمان بیماری های جسمانی ، آرامش اعصاب  وروان",
        preparation: ".به صورت گل بابونه خشک یا به شکل مکمل غذایی مصرف کرد",
        side_effects: "عوارض احتمالی شامل حساسیت پوستی ، تحریک گوارش و تحریک سیستم عصبی هستند.",
    },
    {
        name: "رزماری",
        avatarUrl: "../../images/plants/rozmary.png",
        latinName: "Rosemary",
        properties: "دارای خواص ضد عفونی کننده ، ضد التهابی ، تسکین درد مفاصل ، تقویت حافظه و فواید گوارشی است.",
        Uses: "درمان کبد چرب ، سم زدایی کبد ، باعث ادرارآوری و دفع سموم از بدن.",
        preparation: "به صورت دمنوش آن را میتوان نوشید",
        side_effects: "عوارض احتمالی شامل حساسیت پوستی ، تحریک گوارش و تحریک سیستم عصبی هستند.",
    },
    {
        name: "جوانه گندم",
        avatarUrl: "../../images/plants/javane gandom.png",
        latinName: "Wheatgrass",
        properties: "دارای خواص ضد التهابی ، آنتی اکسیدانی ، تقویت سیستم ایمنی و فواید گوارشی است.",
        Uses: " .پیشگیری از انواع بیماری ها مثل سرطان و بیماری های قلبی عروقی وضد پیری است",
        preparation: "میتوان آن را به صورت عصاره جوانه گندم مصرف کرد.",
        side_effects: "عوارض احتمالی شامل تحریک گوارش ، حساسیت پوستی و تحریک سیستم عصبی هستند .",
    },
    {
        name: "زعفران",
        avatarUrl: "../../images/plants/zaferan.png",
        latinName: "Saffron",
        properties: "دارای خواص ضد افسردگی ، آرامبخش ، تسکین درد و تقویت قلبی است.",
        Uses: "کمک به درمان سرطان",
        preparation: "میتوان آن را به صورت نخود زعفران یا به شکل مکمل غذایی مصرف کرد.",
        side_effects: "عوارض احتمالی شامل تحریک گوارش ، حساسیت پوستی و تحریک سیستم عصبی هستند.",
    },
    {
        name: "الوئه ورا",
        avatarUrl: "../../images/plants/aloevera.png",
        latinName: "Aloe Vera",
        properties: "دارای خواص التیام بخش ، آنتی اکسیدانی ، تسکین درد و ترمیم پوست",
        Uses: "کمک به درمان بیماری های پوستی ، درمان زخم",
        preparation: "میتوان آن را به صورت ژل آلوئه ورا استفاده کرد",
        side_effects: "برای زخم های عمیق نمیتوان استفاده کرد ، برای کودکان ممنوع است.",
    },
    {
        name: "جینسنگ",
        avatarUrl: "../../images/plants/jinsing.png",
        latinName: "Ginseng",
        properties: "تقویت سیستم ایمنی ، افزایش انرژی ، ضد استرس ، تقویت حافظه و درمان اختلالات جنسی.",
        Uses: "تب بر ، اثر مقوی ومعالج اکثر بیماری ها ، درمان لرزش های زمان پیری.",
        preparation: "میتوان آن را به صورت ریشه جینسنگ یا به شکل مکمل غذایی مصرف کرد.",
        side_effects: "عوارض احتمالی شامل افزایش فشار خون ، اختلالات خواب ، حساسیت پوستی وتحریک سیستم عصبی هستند.",
    },
    {
        name: "کوهوش سیاه",
        avatarUrl: "../../images/plants/kohooshSiyah.png",
        latinName: "Black Cohosh",
        properties: "ضد افسردگی ، تسکین درد پریودی ، تنظیم هورمون های زنانه و درمان علائم یائسازی",
        Uses: "درمان مشکلات تنفسی از جمله آسم درمان سرما خوردگی ، درمان میگرن",
        preparation: "میتوان آن را به صورت ریشه کوهوش سیاه یا به شکل مکمل غذایی مصرف کرد",
        side_effects: "عوارض احتمالی شامل درد شکمی ، سر درد ، حساسیت پوستی و تحریک سیستم عصبی هستند.",
    },
    {
        name: "خارمریم",
        avatarUrl: "../../images/plants/kharmaryam.png",
        latinName: "Milk Thistle",
        properties: "تقویت کبد ، حفظ سلامتی کبد ، ضد التهابی و آنتی اکسیدانی.",
        Uses: "درمان بیماری های کبد ، سم زدایی کبد ، پیشگیری از سرطان.",
        preparation: "میتوان از دمنوش آن استفاده کرد یا به صورت ترکیب آن با آب استفاده کرد",
        side_effects: "عوارض احتمالی شامل تحریک معده ، اسهال و حساسیت پوستی هستند.",
    },
    {
        name: "رازیانه",
        avatarUrl: "../../images/plants/razyaneh.png",
        latinName: "Fennel",
        properties: "تسکین درد شکمی ، تقویت دستگاه گوارش وکاهش سرگیجه",
        Uses: "کمک به کم خونی ، کمک به سوءهاضمه ، رفع اسهال و اختلالات قاعدگی ویبوست و نفخ",
        preparation: "میتوان دمنوش آن را تهیه کرد و نوشید",
        side_effects: "عوارض احتمالی شامل حساسیت پوستی و تحریک سیستم عصبی هستند",
    },
    {
        name: "اسطوخودوس",
        avatarUrl: "../../images/plants/ostokhodos.png",
        latinName: "Lavender",
        properties: "ضد التهابی ، آرامبخش ، تسکین درد و بهبود خواب",
        Uses: "کاهش ابتلا به بیماری های قلب عروقی ، گردش خون را بهبود میبخشد ، باعث تنظیم ضربان قلب وکنترل تپش قلب",
        preparation: "میتوان آن را به صورت اسطوخودوس خشک یا روغن اسطوخودوس استفاده کرد",
        side_effects: "عوارض احتمالی شامل حساسیت پوستی و تحریک سیستم عصبی هستند.",
    },
    {
        name: "ریحان",
        avatarUrl: "../../images/plants/reyhan.png",
        latinName: "Basil",
        properties: "تسکین درد التهاب ، تقویت سیستم ایمنی ،کاهش ریسک بیماری های قلبی و عروقی و تسکین علائم التهابی دستگاه تنفسی .",
        Uses: ".کاهش ورم مفاصل ، درمان پوکی استخان ، درمان اسهال ، ازبین بردن خستگی و استرس",
        preparation: "میتوانید از برگ های آن استفاده کنید و همچنین میتوانید از روغن ریحان استفاده کنید.",
        side_effects: "مصرف بیش از حد ریحان ممکن است باعث ایجاد مشکلات گوارشی ، افزایش خونریزی های دوران قاعدگی و اختلالات خواب شود.",
    },
    {
        name: "گلرنگ",
        avatarUrl: "../../images/plants/golrang.png",
        latinName: "Safflower",
        properties: "تسکین درد ، تسکین التهاب ، تقویت سیستم ایمنی ، کاهش ریسک بیماری های قلبی و عروقی وتسکین علائم التهابی دستگاه تنفسی",
        Uses: "رفع فلج های ناگهانی بر اثر سکته ، برطرف کردن بیماری های ریوی.",
        preparation: "میتوان آن را به صورت پودر گلرنگ یا به شکل مکمل غذایی مصرف کرد.",
        side_effects: "عوارض احتمالی شامل حساسیت پوستی ، افزایش خونریزی و کاهش فشار خون هستند.",
    },
    {
        name: "زرشک",
        latinName: "Barberry",
        avatarUrl: "../../images/plants/zereshk.png",
        properties: "کاهش التهاب ، تقویت سیستم ایمنی ، کاهش فشار خون ، کاهش قند خون ، و تسکین درد مفاصل",
        Uses: "درمان گلو درد ، گرفتگی بینی ، درمان سینوزیت ، درمان عفونت های پوستی.",
        preparation: "برای تهیه زرشک میتوانید از برگ های آن استفاده کنید و همچنین ، در قالب چای یا عرقیجات جانبی آن ممکن است.",
        side_effects: "عوارض همچون تب ، تهوع و اسهال",
    },
    {
        name: "نعنا",
        avatarUrl: "../../images/plants/nana.png",
        latinName: "Peppermint",
        properties: "تسکین درد شکم ، کاهش اظطراب ، کاهش سر درد کاهش عفونت های دستگاه تنفسی و تقویت سیستم گوارشی .",
        Uses: "درمان نفخ شکم ، درمان درد های قاعدگی ، درمان اسهال ، درمان تهوع ، درمان افسردگی ، درمان سرما خوردگی .",
        preparation: "برای تهیه نعنا میتوانید از برگ ها و گل های آن استفاده کنید و همچنین میتوانید چایی یا روغن اسانس آن را مصرف کنید.",
        side_effects: "مصرف بیش از حد نعنا  ممکن است باعث اسهال ، بی خوابی و تحریک سیستم گوارشی شود.",
    },
    {
        name: "جعفری",
        avatarUrl: "../../images/plants/jafari.png",
        latinName: "Parsley",
        properties: "ضد التهاب ، ضد تشنج ، دفع سموم بدن، تصفیه خون ، تقویت سیستم ایمنی بدن ، ضد اضطراب .",
        Uses: "درمان التهاب های مفصلی ، درمان کیست های رحم ، درمان عفونت های ادراری ، کاهش التهاب های پوستی ، تصفیه خون ، تقویت سیستم ایمنی بدن ، کاهش اضطراب و استرس .",
        preparation: "میتوان به صورت خرد شده یا کامل مصرف کرد و همچنین میتوان به ع نوان چاشنی غذا ها استفاده کرد .",
        side_effects: "تحریک پوستی ، تحریک دستگاه گوارش ، حساسیت پوستی .",
    },
    {
        name: "فلفل سیاه",
        avatarUrl: "../../images/plants/felfelSiyah.png",
        latinName: "Piper nigrum",
        properties: "ضد التهاب ، ضد باکتری ، ضد ویروس ، ضد قارچ ، تسکین دهنده درد ، تنظیم کننده هورمون های جنسی ، تقویت کننده سیستم ایمنی بدن ، تنظیم کننده قشار خون",
        Uses: "درمان درد های مفصلی ، سرماخوردگی ، درمان عفونت های روده ، درمان نفخ و درد شکم ، درمان بیماری های قلبی و عروقی ، درمان سرطان ، تسکین دهنده درد ، و التهاب ، تقویت کننده حافظه و تمرکز ، تنظیم کننده هورمون های جنسی.",
        preparation: "مصرف فلفل سیاه به صورت پودر ، مصرف فلفل سیاه به صورت عرقیجات ، مصرف فلفل سیاه به صورت دم کرده مصرف فلفل سیاه به صورت خشک کردن و اسپری ،مصرف فلفل سیاه به صورت خوراکی در  تهیه غذا های سنتی ",
        side_effects: "تحریک دستگاه گوارش ، حساسیت پوستی ، افزایش ترشح اسید معده ، افزایش خطر بروز بیماری های خونریزی ، تحریک دستگاه عصبی ، تحریک دستگاه قلبی.",
    },
    {
        name: "سدر",
        avatarUrl: "../../images/plants/sedr.png",
        latinName: "Ziziphus spina-christi",
        properties: "ضد التهاب ، ضد باکتری ، ضد ویروس ،ضد قارچ ، تسکین دهنده درد ، تسکین دهنده سرفه و آسم ، تسکین دهنده علائم سوء هاضمه ، تنظیم کننده هورمون های جنسی .",
        Uses: "درمان درد های معده ، درمان بیماری های ریوی مانند آسم و سرفه ،درمان نفخ و درد شکم ، درمان کم خونی ، درمان بیماری های قلبی و عروقی ، درمان بیماری های پوستی مانند عفونت های پوستی و خارش .",
        preparation: "مصرف سدر به صورت پودر ، مصرف سدر به صورت عرقیجات ، مصرف سدر به صورت دم کرده ، مصرف سدر به صورت خشک کردن و اسپری ، مصرف سدر به صورت خوراکی در تهیه غذا های سنتی .",
        side_effects: "تحریک دستگاه گوارش ، حساسیت پوستی ، تحریک دستگاه عصبی ، تحریک دستگاه ادراری .",
    },
    {
        name: "هل",
        avatarUrl: "../../images/plants/hel.png",
        latinName: "Elettaria cardamomum",
        properties: "ضد التهاب ، ضد باکتری ، تقویت کننده دستگاه گوارش ، ضد افسردگی ، تسکین دهنده درد ، ضد اضطراب ..",
        Uses: " کاهش علائم سوء هاضمه ، درمان نفخ ، درمان عفونت های دستگاه گوارش ، درمان بیماری های عفونی و التهابی ، درمان افسردگی و اضطراب ، تسکین درد ، بهبود عملکرد جنسی .",
        preparation: "مصرف هل به صورت پودر ، مصرف هل به صورت عصاره ، مصرف هل به صورت عرقیجات ، مصرف هل در تهیه عصاره های طب سنتی .",
        side_effects: "حساسیت پوستی ، تحریک دستگاه گوارش ، تحریک دستگاه تنفس ، سر درد ، بیخوابی ، افزایش احتمال خونریزی ، در بیماری های که دارای بیماری های خونی هستند .",
    },
    {
        name: "اکیناسه",
        avatarUrl: "../../images/plants/okinase.png",
        latinName: "Echinacea purpurea",
        properties: "تقویت کننده سیستم ایمنی بدن ، ضد التهاب ، ضد عفونب کننده ، آنتی اکسیدان ، تسکین دهنده درد .",
        Uses: "پیشگیری و درمان سرماخوردگی ، آنفولانزا و عفونت های تنفسی ، درمان عفونت های قارچی و باکتریایی ، درمان التهاب هاب مفصلی ، درمان زخم های پوستی ، تسکین در ، تقویت کننده سیتم ایمنی بدن .",
        preparation: "مصرف اکیناسه به صورت قرص و کپسول به شکل دارو ، مصرف اکیناسه دز شکل عصاره های گیاهی ، مصرف اکیناسه در تهیه عصاره های طب سنتی.",
        side_effects: "حساسیت پوستی ، تحریک دستگاه گوارش ، سر درد ، بی خوابی ، افزایش خطر بروز ، بیماری های خونریزی .",
    },
    {
        name: "کرفس",
        avatarUrl: "../../images/plants/karafs.png",
        latinName: "Apium graveolens",
        properties: "ضد التهاب ، ضد باکتری ، ضد ویروس ، ضد قارچ ، تقویت کننده سیستم ایمنی بدن ،تسکین دهنده درد ، تنظیم کننده فشار خون ، تسکین دهنده استرس و اضطراب ، کاهش خطر بروز بیماری های قلبی و عروقی",
        Uses: "کاهش علائم التهاب مفاصل ، کاهش علايم سوء هاضمه ، کاهش علائم استرس و اضطراب ، کاهش خطر بروز بیماری های قلبی و عروقی ، تنظیم فشار خون ، تسکین درد .",
        preparation: "مصرف کرفس به صورت پودر ، مصرف کرفس به صورت عرقیجات ، مصرف کرفس در تهیه غذا های سنتی .",
        side_effects: "تحریک دستگاه گوارش ، حساسیت پوستی ، تحریک دستگاه ادراری ، تحریک دستگاه عصبی .",
    },
    {
        name: "دارچین",
        avatarUrl: "../../images/plants/darchin.png",
        latinName: "Cinnamomum verum",
        properties: "ضد التهاب ، ضد بیماری های قلبی ، ضد بیماری های دیابتی ، ضد عفونی کننده ، تقویت کننده سیستم ایمنی بدن ، ضد اضطراب و افسردگی .",
        Uses: "کاهش فشار خون ، کاهش قند خون ، کاهش کلسترول خون ، پیشگیری و درمان ، بیماری های قلبی ، پیشگیری و درمان ، بیماری های دیابتی ، درمان عفونت های ریه ، درمان عفونت های قارچی و باکتریایی ، تسکین دهنده درد ، ضد اضطراب و استرس .",
        preparation: "استفاده از دارچین به صورت پودر در غذا ، استفاده از عصاره های گیاهی دارچین در شکل قرص و کپسول ، استفاده از دارچین در تهیه عصاره های طب سنتی .",
        side_effects: "حساسیت پوستی ، تحریک دستگاه گوارش ، افزایش خونریزی در بیماران مبتلا به بیماری های خونریزی ،‌کاهش فشار خون در بیماران مبتلا به فشار خون",
    },
    {
        name: "گشنیز",
        avatarUrl: "../../images/plants/gishniz.png",
        latinName: "Coriaandrum sativum",
        properties: "ضد التهاب ، ضد تشنج ، تقویت کلیه ، تسکین دهنده درد ، آرامبخش ، دفع سموم بدن ، ضد اضطراب و افسردگی .",
        Uses: "درمان التهاب های پوستی ، درمان التهاب معده و روده ، درمان سرفه و سرما خوردگی ، کاهش در عضلانی ، تقویت کلیه ، تسکین دهنده درد ، کاهش اضطراب و استرس ، دفع سموم بدن",
        preparation: "ریختن یک قاشق غذا خوری از بذر هاب گشنیز در یک فنجان آب جوش و نوشیدن آن پس از گرم شدن ، استفاده از عصاره های گیاهی گشنیز در شکل قرص و کپسول ، استفاده از روغن گیاهی گشنیز برای ماساژ و استحمام.",
        side_effects: "تحریک پوستی ، تحریک دستگاه گوارش ، حساسیت پوستی .",
    },
    {
        name: "سیاه دانه",
        avatarUrl: "../../images/plants/siyahDane.png",
        latinName: "ٔigella sativa",
        properties: "ضد التهاب ، ضد تشنج ، ضد بیماری های قلبی ، ضد بیماری های کبدی ، ضد بیماری های سرطان ، تسکین دهنده درد ، دفع سموم بدن ، تقویت سیستم ایمنی بدن ،ضد اضطراب و افسردگی .",
        Uses: "درمان التهاب هاب پوستی ، درمان التهاب معده و روده ، کاهش فشار خون ، کاهش قند خون ، کاهش کلسترول خون ، درمان بیماری های کبدی ، درمان بیماری های سرطانی ، تسکین دهنده درد، دفع سموم بدن ، تقویت سیستم ایمنی بدن ،ضد اضطراب و افسردگی",
        preparation: "ریختن یک قاشق چایخوری از بذر های خشک ختمی در یک فنجان آب جوش ،و نوشیدن آن پس از گرم شدن ، استفاده از عصاره های گیاهی ختمی در شکل قرص و کپسول ، استفاده از روغن گیاهی ختمی برای ماساژ و استحمام .",
        side_effects: "تحریک پوستی ، تحریک دستگاه گوارش ، حساسیت پوستی ، کاهش قند خون در برخی موارد .",
    },
    {
        name: "سیر",
        avatarUrl: "../../images/plants/sir.png",
        latinName: "Allium sativum",
        properties: "ضد التهاب ، ضد بیماری های قلبی ، ضد بیماری های سرطانی ، ضد عفونی کننده ، تسکین دهنده درد ، خنثی کننده سموم بدن ، تقویت کننده سیستم ایمنی بدن .",
        Uses: "پیشگیری و درمان بیماری های قلبی ، پیشگیری و درمان بیمارسی های  سرطانی ، درمان عفونت های ریه ، گلو درد و سینوزیت ، کاهش فشار خون ، کاهش قند خون ، کاهش کلسترول خون ،درمان زخم های داخلی و خارجی ، درمان عفونت های قارچی وو باکتریایی ،تسکین دهنده درد ، خنثی کننده سموم بدن ، تقویت کننده سیستم ایمنی بدن . ",
        preparation: "مصرف سیر فرآورده هایی مانند روغن سیر و عصاره های گیاهی سیر ، مصرف سیر خام در غذاها ، مصرف سیر به صورت قرص و کپسول در شکل دارو ، استفاده از سیر در تهیه عصاره های طب سنتی .",
        side_effects: "تحریک پوستی ، تحریک دستگاه گوارش ، بوی نامطبوع دهان ، افزایش خونریزی در بیماران مبتلا به بیماری های خونریزی ، خفگی در بیماران مبتلا به بیماری های ریه و آسم ، کاهش فشار خون در بیماران مبتلا به فشار خون پایین .",
    },
    {
        name: "باد رنجبویه",
        avatarUrl: "../../images/plants/‌‌Badranjbooye.png",
        latinName: "Borago officinalis",
        properties: "ضد التهاب ، ضد تشنج ، ضد بیماری های قلبی ، ضد بیماری های روماتیسمی ، تسکین دهنده درد ، خنثی کننده سموم بدن ، تقویت سیستم ایمنی بدن ، ضد اضطرایب و افسردگی .",
        Uses: "درمان التهاب های پوستی ، درمان التهاب معده و روده ، درمان عفونت های ادراری ، کاهش فشار خون ، کاهش قند خون ، کاهش کلسترول خون ، درمان بیماری های قلبی ، درمان بیماری های روماتیسمی ، تسکین دهنده درد ، خنثی کننده سموم بدن ، تقویت سیستم ایمنی بدن ، کاهش اضطرب و استرس .",
        preparation: "استفاده از برگ های تازه یا خشک بادرنجبویه به صورت چای ، استفاده از عصاره های گیاهی بادرنجبویه در شکل قرص و کپسول ، استفاده از روغن گیاهی بادرنجبویه برای ماساژ و استحمام .",
        side_effects: "تحریک پوستی ، تحریک دستگاه گوارش ، حساسیت پوستی ، کاهش قند خون در برخی موارد .",
    },
    // {
    //     name: "صمغ عربی",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
    // {
    //     name: "بومادران زرد",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
    // {
    //     name: "دم اسب",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
    // {
    //     name: "زر آوند سفید",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
    // {
    //     name: "گل ختمی",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
    // {
    //     name: "غازیاقی",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
    // {
    //     name: "کنجک",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
    // {
    //     name: "تیره آلاله",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
    // {
    //     name: "سنبل ختایی",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
    //
    // {
    //     name: "دنگ کوئی",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
    //
    // {
    //     name: "بابا آدم",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
    //
    // {
    //     name: "همیشه بهار",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
    //
    // {
    //     name: "آستر اگالوس",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
    //
    // {
    //     name: "شابیزک",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
    //
    // {
    //     name: "چریش",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
    //
    // {
    //     name: "کنجک",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
    //
    // {
    //     name: "دیزی",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
    //
    // {
    //     name: "شابانک",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
    // {
    //     name: "چیلی",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
    // {
    //     name: "پاپایا",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
    // {
    //     name: "سنا",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
    // {
    //     name: "قات",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
    // {
    //     name: "خربزه گیاهی",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
    // {
    //     name: "گل گندم آبی",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
    // {
    //     name: "علف و تیور",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
    // {
    //     name: "گنه گنه",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
     // {
    //     name: "نارنج",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
    // {
    //     name: "لیمو",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
     // {
    //     name: "نارنج سه برگ",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
    // {
    //     name: "عصاره ی آبی اکایپتوس",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
     // {
    //     name: "زالزالک",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
    // {
    //     name: "زردچوبه",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
     // {
    //     name: " کیپریپدیوم های زرد",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
    // {
    //     name: "گل انگشتانه",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
     // {
    //     name: "سرخارگل",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
    // {
    //     name: "یرباسانتا",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
     // {
    //     name: "شقایق کالیفرنیا",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
    // {
    //     name: "اکالیپتوس",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
     // {
    //     name: "شمشاد سرخ",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
    // {
    //     name: "آسم",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
     // {
    //     name: "نخل آسای",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
    // {
    //     name: "آنقوزه",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
     // {
    //     name: "سیاه توسه",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
    // {
    //     name: "شاه تره",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
     // {
    //     name: "گل برفی",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
    // {
    //     name: "شمعدانی",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
     // {
    //     name: "جینکو",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
    // {
    //     name: "پاپیتال",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
     // {
    //     name: "هاماملیس انجیلی",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
    // {
    //     name: "سنجد تلخ",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
     // {
    //     name: "هودیا گوردونوی",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
    // {
    //     name: "خوک طلایی",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
     // {
    //     name: "گل راعی",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
    // {
    //     name: " یربا مایت",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
     // {
    //     name: "بادیان رومی",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
    // {
    //     name: "یاسمن سفید",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
     // {
    //     name: "اسکابیوزا",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
    // {
    //     name: "تیغ بیلوط کوتاه",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
     // {
    //     name: "برگ بو",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
    // {
    //     name: "حنا",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
     // {
    //     name: "کتان",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
    // {
    //     name: "ماگنولیا",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
     // {
    //     name: "پنیرک",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
    // {
    //     name: "یونجه",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
     // {
    //     name: "روغن درخت چای",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
    // {
    //     name: "کراتوم",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
     // {
    //     name: "بیتر ملون",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
    // {
    //     name: "نونی",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
      // {
    //     name: "گز روغنی",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },  // {
    //     name: "آب تره",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },  // {
    //     name: "لوتوس",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },  // {
    //     name: "گل مغربی",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },  // {
    //     name: "مرزنگوش",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },  // {
    //     name: "خشخاش",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },  // {
    //     name: "گل ساعتی",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },  // {
    //     name: "اسپند",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },  // {
    //     name: "کاوا",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },  // {
    //     name: "غال اخته جامیکی",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },  // {
    //     name: "بارهنگ",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
     // {
    //     name: "گل بادبادک",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
     // {
    //     name: "پلمنیوم رپتنس",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
     // {
    //     name: "گواوا",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
     // {
    //     name: "خاکستر زننده",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
     // {
    //     name: "کواسیا آمارا",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
     // {
    //     name: "شیرتیغک",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
     // {
    //     name: "گل میمونی",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
     // {
    //     name: "ترشک",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
     // {
    //     name: "بید",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
     // {
    //     name: "مریم گلی",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
     // {
    //     name: "آقطی",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
     // {
    //     name: "صندل",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
     // {
    //     name: "صبر زرد",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
     // {
    //     name: "مرزه",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
     // {
    //     name: "کانا",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
     // {
    //     name: "خرفه",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
     // {
    //     name: "گل مینای آبی کوهی",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
     // {
    //     name: "دانه قناری",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
     // {
    //     name: "کاروی",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
     // {
    //     name: "هماور طبی",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
     // {
    //     name: "میخک",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
       // {
    //     name: "قاصدک",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },

       // {
    //     name: "مریم نخودی",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },

       // {
    //     name: "نمدر برگ ریز",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },

       // {
    //     name: "زیر بنا",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },

       // {
    //     name: "ترما ارینتالیس",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },

       // {
    //     name: "شبدر قرمز",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },

       // {
    //     name: "شنبلیله",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
      // {
    //     name: "علف گندم",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
          // {
    //     name: "توسکای سفید",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
          // {
    //     name: "گیاه پنجه گربه",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
          // {
    //     name: "گزنه",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
          // {
    //     name: "زغال اخته آبی",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
          // {
    //     name: "کرنبری",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
          // {
    //     name: "قره گلیه",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
          // {
    //     name: "مولین",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
          // {
    //     name: "شاه پسند",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
          // {
    //     name: "برگ تلخ",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
          // {
    //     name: "سیزاب",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
          // {
    //     name: " تیره ویبورنوم",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
           // {
    //     name: "بنفشه وحشی",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
           // {
    //     name: "دارواش",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
           // {
    //     name: "پنج انگشت",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
           // {
    //     name: "انگور",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
           // {
    //     name: "نهال گردو",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },
           // {
    //     name: "آشواگاندها",
    //     latinName: "",
    //     properties: "",
    //     Uses: "",
    //     preparation: "",
    //     side_effects: "",
    // },   
]



